// React
import React, { useState } from 'react';

// Next
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '@/styles/Home.module.css';

// axis
import axios from 'axios';

// images
import marioBackground from '../../public/images/marioBackground.jpeg';

const Home: NextPage = () => {
  const [userAnswer, setUserAnswer] = useState('');

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    try {
      const { data } = await axios.post('/api/check-answer', { answer: userAnswer });
      console.log(data);
    } catch (err) {
      console.log(err);
    }
  };

  return (
    <>
      <Head>
        <title>Scavenger Hunt</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div style={{ position: 'absolute', height: '100%', width: '100%' }}>
          <Image src={marioBackground} alt="Mario" layout="fill" objectFit="contain" />
          <div className={styles.titleContainer}>
            <h1 className={styles.title}>Scavenger Hunt</h1>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
