// React
import React, { useState } from 'react';

// Next
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '@/styles/Home.module.scss';

// axis
import axios from 'axios';

// images
import marioTitle from '../../public/images/Mario_Series_Logo.svg';
import mario from '../../public/images/mario.png';

const Home: NextPage = () => {
  const [userAnswer, setUserAnswer] = useState('');

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    try {
      const { data } = await axios.post('/api/check-answer', { answer: userAnswer });
      console.log(data);
    } catch (err) {
      console.log(err);
    }
  };

  return (
    <>
      <Head>
        <title>Scavenger Hunt</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Image src={marioTitle} alt="Super Mario" height={100} width={200} />
        <h1 className={styles.title}>SCAVENGER HUNT</h1>
        <button className="btn">Let&apos;s Go!</button>
        <Image src={mario} alt="Mario" />
      </main>
    </>
  );
};

export default Home;
