// React
import React, { useState } from 'react';

// Next
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '@/styles/Home.module.css';

// axis
import axios from 'axios';

const Home: NextPage = () => {
  const [userAnswer, setUserAnswer] = useState('');

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    try {
      const { data } = await axios.post('/api/check-answer', { answer: userAnswer });
      console.log(data);
    } catch (err) {
      console.log(err);
    }
  };

  return (
    <>
      <Head>
        <title>Scavenger Hunt</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>Scavenger Hunt</h1>
        <form onSubmit={handleSubmit}>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati maxime vitae amet eos ut voluptas itaque
            quis provident odio fugit?
          </p>
          <input value={userAnswer} onChange={(e) => setUserAnswer(e.target.value)} />
          <button type="submit">Submit</button>
        </form>
      </main>
    </>
  );
};

export default Home;
